class UserError(Exception):
    pass

class CollectError(Exception):
    pass
